version: '2'
services:
  api:
    image: "node:9"
    volumes:
      - ./:/server
    working_dir: /server
    command: node app.js
    ports:
     - "3000:3000"
    links:
      - redis-for-rnkm-redis-ha-master-svc
      - datanaliez-api-logdb-influxdb
  sentinel:
    image: "node:9"
    volumes:
      - ./:/server
    working_dir: /server
    command: node sentinel.js
    links:
      - redis-for-rnkm-redis-ha-master-svc
    # networks:
    #   - datanaliez-cluster
  datanaliez-api-logdb-influxdb:
    image: "influxdb:1.4-alpine"
    ports:
     - "8086:8086"
  redis-for-rnkm-redis-ha-master-svc:
    image: "redis:3.2"
# networks:
#   datanaliez-cluster:
#     external:
#       name: datanaliez_default
