version: '2'
services:
  api:
    image: "node:9"
    volumes:
      - ./:/server
    working_dir: /server
    command: node app.js
    ports:
     - "3000:3000"
    links:
      - redis-for-rnkm-redis-ha-master-svc
    # networks:
    #   - datanaliez-cluster
  redis-for-rnkm-redis-ha-master-svc:
    image: "redis:3.2"
# networks:
#   datanaliez-cluster:
#     external:
#       name: datanaliez_default
