# apiVersion: v1
# kind: Service
# metadata:
#   name: rnkm2018-middle-api
#   labels:
#     app: rnkm2018-middle-api
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 443
#     targetPort: 3000
#   selector:
#     app: rnkm2018-middle-api-worker
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rnkm2018-middle-api-worker
  labels:
    app: rnkm2018-middle-api-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rnkm2018-middle-api-worker
  template:
    metadata:
      labels:
        app: rnkm2018-middle-api-worker
    spec:
      containers:
      - name: rnkm2018-middle-api-worker
        image: gcr.io/skylab-184008/rnkm_middle_api:1.0.15
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/chkStatus
            port: 3000
            scheme: HTTPS
          initialDelaySeconds: 3
          periodSeconds: 20
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: middle-api-sentinel
  labels:
    app: middle-api-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middle-api-sentinel
  template:
    metadata:
      labels:
        app: middle-api-sentinel
    spec:
      containers:
      - name: middle-api-sentinel
        image: gcr.io/skylab-184008/rnkm_middle_api_sentinel:1.0.4
        imagePullPolicy: Always
